ProjectMakeMoney.v1/ProjectMakeMoney.v1/Areas/Admin/Controllers/MD_NganHangController.cs
using Library.YTB.BO.Models;
using Library.YTB.Utils;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace ProjectMakeMoney.v1.Areas.Admin.Controllers
{
    [Authorize(Roles = "TL0009")]
    public class MD_NganHangController : Controller
    {
        // GET: Admin/MD_NganHang
        private Library.YTB.DA.NganHang.DA_NganHang da_nganhnag = null;

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpGet]
        public ActionResult GET(PagingParam pagingParam, string tennganhang = null, bool? isActive = null)
        {
            da_nganhnag = new Library.YTB.DA.NganHang.DA_NganHang();
            ApiResult apiResult = da_nganhnag.GET(pagingParam, tennganhang, isActive);
            return Json(apiResult, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult GETID(int? id)
        {
            da_nganhnag = new Library.YTB.DA.NganHang.DA_NganHang();
            ApiResult apiResult = da_nganhnag.GETID(id);
            return Json(apiResult, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult Create(MD_NganHang nh)
        {
            if (!ModelState.IsValid)
            {
                return Json(new ApiResult() { success = false, message = "không thể tạo yêu cầu", data = null }, JsonRequestBehavior.AllowGet);
            }
            da_nganhnag = new Library.YTB.DA.NganHang.DA_NganHang(User.Identity.Name);
            ApiResult apiResult = da_nganhnag.Create(nh);
            return Json(apiResult, JsonRequestBehavior.AllowGet);
        }

        [HttpDelete]
        public ActionResult DELETE(int? id)
        {
            da_nganhnag = new Library.YTB.DA.NganHang.DA_NganHang();
            ApiResult apiResult = da_nganhnag.DELETE(id);
            return Json(apiResult, JsonRequestBehavior.AllowGet);
        }

        [HttpPut]
        public ActionResult IsActive(int? id)
        {
            da_nganhnag = new Library.YTB.DA.NganHang.DA_NganHang();
            ApiResult apiResult = da_nganhnag.IsActive(id);
            return Json(apiResult, JsonRequestBehavior.AllowGet);
        }
    }
}

ProjectMakeMoney.v1/ProjectMakeMoney.v1/Areas/Admin/Views/MD_NganHang/Create.cshtml
@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Thêm Ngân Hàng
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Ngân Hàng</li>
    </ol>
</section>
<!-- Main content -->
<!-- Main content -->
<section class="content">
    <!-- Info boxes -->
    <div class="row">
        <div class="col-md-12 col-sm-6 col-xs-12">
            @using (Html.BeginForm("Create", "MD_NganHang", FormMethod.Post, new { id = "frmNganHang" }))
            {
                <div class="box box-default">
                    <div class="box-header with-border">
                        <h3 class="box-title">Tạo Ngân Hàng</h3>
                        <div class="box-tools pull-right">
                            <button type="button" class="btn btn-box-tool" data-widget="collapse">
                                <i class="fa fa-minus"></i>
                            </button>
                        </div>
                        <!-- /.box-tools -->
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="inputPassword3" class="col-sm-2 control-label input-sm">Tên ngân hàng</label>
                                <div class="col-sm-10">
                                    <input type="text" class="form-control input-sm" id="TenNganhang" name="TenNganhang" placeholder="Tên ngân hàng">
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="col-sm-2"></div>
                            <div class="col-sm-2" style="margin-top: 5px">
                                <input type="checkbox" name="isActive" id="isActive" checked="checked" value="true"> Kích hoạt
                            </div>
                            <div class="col-sm-8"></div>
                        </div>
                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer" style="">
                        <button type="submit" id="btnUpdate" class="btn btn-primary btn-flat pull-right" style="margin-right: 25px">Tạo mới</button>
                        <button type="reset" id="clearFrm" class="btn btn-default btn-flat pull-right" style="margin-right: 25px">Làm mới</button>
                    </div>
                    <div class="overlay" id="overlay">
                        <i class="fa fa-refresh fa-spin"></i>
                    </div>
                </div>
                <!-- /.box -->
            }
        </div>
    </div>
    <!-- /.row -->
</section>

@section Script{
    <script>
    $(function () {
        $(".overlay").hide();
    });
    var frmNganHang = $("#frmNganHang");
    frmNganHang.submit(function (e) {
        $(".overlay").show();
            e.preventDefault();
            $.ajax({
                type: 'POST',
                url: frmNganHang.attr('action'),
                data: frmNganHang.serialize(),
                success: function (data) {
                    if (data.success) {
                        $.notify(data.message, "success");
                    } else { $.notify(data.message, { position: "top right", className: "error" }); }
                    $(".overlay").hide();
                },
                error: function (data) {
                    $.notify("Tạo thông tin thất bại", { position: "top right", className: "error" });
                    $(".overlay").hide();
                },
            });
        });
    </script>
}

ProjectMakeMoney.v1/ProjectMakeMoney.v1/Areas/Admin/Views/MD_NganHang/index.cshtml
@{
    ViewBag.Title = "index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Ngân Hàng
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Ngân Hàng</li>
    </ol>
</section>
<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-md-12 col-sm-6 col-xs-12">
            <div class="box">
                <div class="box-header">
                    <div class="col-sm-3">
                        <h3 class="box-title">Quản lý ngân hàng</h3>
                    </div>
                   
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <div id="table_example" class="dataTables_wrapper form-inline dt-bootstrap">
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="dataTables_length">
                                    <label>
                                        Show
                                        <select id="example-category-length" class="form-control input-sm">
                                            <option value="10">10</option>
                                            <option value="25">25</option>
                                            <option value="50">50</option>
                                            <option value="100">100</option>
                                        </select>
                                        entries
                                    </label>
                                </div>
                            </div>
                            <div class="col-sm-3">
                                <div id="example1_filter" class="dataTables_filter">
                                    <label>Search:<input id="TenMenu-search" type="search" class="form-control input-sm" placeholder="search" /></label>
                                </div>
                            </div>
                            <div class="col-sm-3">
                                <div id="example1_filter" class="dataTables_filter">
                                    <label>
                                        Trạng thái
                                        <select id="trangthai-search" class="form-control input-sm">
                                            <option value="true">Active</option>
                                            <option value="false">No Active</option>
                                        </select>
                                    </label>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-12">
                                <table id="example-category" class="table table-bordered table-striped dataTable"></table>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-5">
                                <div class="dataTables_info" id="example-categry-info" role="status">Showing 1 to 10 of 57 entries</div>
                            </div>
                            <div class="col-sm-7">
                                <div class="dataTables_paginate paging_simple_numbers" id="example1_paginate">
                                    <ul class="pagination">
                                        <li class="paginate_button previous" id="example_previous">
                                            <a class="Button">Previous</a>
                                        </li>
                                        <li class="paginate_button active" id="example-curent">
                                            <a aria-controls="example2" data-dt-idx="6" tabindex="0">6</a>
                                        </li>
                                        <li class="paginate_button next" id="example_next">
                                            <a class="Button">Next</a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.box-body -->
            </div>
        </div>
    </div>
</section>
<!-- /.content -->

@section Script{
    <script src="~/Areas/Admin/Script/MD_nganhang.js"></script>
}