ProjectMakeMoney.v1/ProjectMakeMoney.v1/Areas/Admin/Controllers/KenhController.cs
using Library.YTB.Utils;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjectMakeMoney.v1.Areas.Admin.Controllers
{
    [Authorize(Roles = "TL0006")]
    public class KenhController : Controller
    {
        private Library.YTB.DA.Kenh.DA_Kenh da_kenh = null;
        private Library.YTB.Utils.ApiResult apiResult = null;
        // GET: Admin/Kenh
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Create()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Edit(int? idKenh)
        {
            da_kenh = new Library.YTB.DA.Kenh.DA_Kenh();
            if (idKenh == null)
                return RedirectToAction("Index", "Home");
            if (!da_kenh.CheckQuantityInID(idKenh))
                return RedirectToAction("Index", "Home");

            ViewBag.id = idKenh;
            return View();
        }

        [HttpGet]
        public ActionResult Detail(int? idKenh)
        {
            da_kenh = new Library.YTB.DA.Kenh.DA_Kenh();
            if (idKenh == null)
                return RedirectToAction("Index", "Home");
            if (!da_kenh.CheckQuantityInID(idKenh))
                return RedirectToAction("Index", "Home");
            ViewBag.id = idKenh;
            return View();
        }

        [HttpGet]
        public ActionResult GET(Library.YTB.Utils.PagingParam pagingParam, string tenkenh, string EmailKenh, string sdt, bool? isPopular, bool? isPrioritize, bool? isactive)
        {
            da_kenh = new Library.YTB.DA.Kenh.DA_Kenh();
            apiResult = da_kenh.GET(pagingParam, tenkenh, EmailKenh, sdt, isPopular, isPrioritize, isactive);
            return Json(apiResult, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult GETID(int? idKenh)
        {
            da_kenh = new Library.YTB.DA.Kenh.DA_Kenh();
            apiResult = da_kenh.GETID(idKenh);
            return Json(apiResult, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult Create(Library.YTB.BO.Models.Kenh ks)
        {
            if (!ModelState.IsValid)
            {
                return Json(new ApiResult() { success = false, message = "không thể tạo yêu cầu", data = null }, JsonRequestBehavior.AllowGet);
            }

            da_kenh = new Library.YTB.DA.Kenh.DA_Kenh(User.Identity.Name);
            apiResult = da_kenh.Create(ks);
            return Json(apiResult, JsonRequestBehavior.AllowGet);
        }

        [HttpPut]
        public ActionResult Edit(int idKenh, Library.YTB.BO.Models.Kenh ks)
        {
            if (!ModelState.IsValid)
                return Json(new ApiResult() { success = false, message = "không thể tạo yêu cầu", data = null }, JsonRequestBehavior.AllowGet);

            da_kenh = new Library.YTB.DA.Kenh.DA_Kenh(User.Identity.Name);
            apiResult = da_kenh.Edit(idKenh, ks);
            return Json(apiResult, JsonRequestBehavior.AllowGet);
        }

        [HttpPut]
        public ActionResult isActive(int? idKenh)
        {
            da_kenh = new Library.YTB.DA.Kenh.DA_Kenh(User.Identity.Name);
            apiResult = da_kenh.isActive(idKenh);
            return Json(apiResult, JsonRequestBehavior.AllowGet);
        }

        [HttpDelete]
        public ActionResult DELETE(int? idKenh)
        {
            da_kenh = new Library.YTB.DA.Kenh.DA_Kenh(User.Identity.Name);
            apiResult = da_kenh.DELETE(idKenh);
            return Json(apiResult, JsonRequestBehavior.AllowGet);
        }
    }
}

ProjectMakeMoney.v1/ProjectMakeMoney.v1/Areas/Admin/Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using System.Text.RegularExpressions;
using Library.YTB.Utils;
using Library.YTB.BO.Models;

namespace ProjectMakeMoney.v1.Areas.Admin.Controllers
{
    [Authorize(Roles = "TL0011")]
    public class MenuController : Controller
    {
        private Library.YTB.DA.Menu.DA_Menu da_menu = null;
        private Library.YTB.Utils.ApiResult apiResult = null;
        // GET: Admin/Menu

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Create()
        {
            return View();
        }

        public ActionResult Edit(int? idMenu)
        {
            da_menu = new Library.YTB.DA.Menu.DA_Menu();
            if (!da_menu.MenuGetItem(idMenu))
                return RedirectToAction("Index", "Home");
            ViewBag.id = idMenu;
            return View();
        }

        [HttpGet]
        public ActionResult GET(PagingParam pagingParam, string TenMenu, bool? trangthai)
        {
            da_menu = new Library.YTB.DA.Menu.DA_Menu();
            apiResult = da_menu.GET(pagingParam, TenMenu, trangthai);
            return Json(apiResult, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult GETID(int? idMenu)
        {
            da_menu = new Library.YTB.DA.Menu.DA_Menu();
            apiResult = da_menu.GETID(idMenu);
            return Json(apiResult, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult Create(Menu sp)
        {
            da_menu = new Library.YTB.DA.Menu.DA_Menu(User.Identity.Name);
            apiResult = da_menu.Create(sp);
            return Json(apiResult, JsonRequestBehavior.AllowGet);
        }

        [HttpPut]
        public ActionResult Edit(int idMenu, Menu sp)
        {
            if (!ModelState.IsValid)
            {
                return Json(new ApiResult() { success = false, message = "không thể tạo yêu cầu", data = null }, JsonRequestBehavior.AllowGet);
            }
            da_menu = new Library.YTB.DA.Menu.DA_Menu(User.Identity.Name);
            apiResult = da_menu.Edit(idMenu,sp);
            return Json(apiResult, JsonRequestBehavior.AllowGet);
        }

        [HttpDelete]
        public ActionResult DELETE(int? idMenu)
        {
            da_menu = new Library.YTB.DA.Menu.DA_Menu(User.Identity.Name);
            apiResult = da_menu.DELETE(idMenu);
            return Json(apiResult, JsonRequestBehavior.AllowGet);
        }

        [HttpPut]
        public ActionResult isActive(int? idMenu)
        {
            da_menu = new Library.YTB.DA.Menu.DA_Menu(User.Identity.Name);
            apiResult = da_menu.isActive(idMenu);
            return Json(apiResult, JsonRequestBehavior.AllowGet);
        }

    }
}

ProjectMakeMoney.v1/ProjectMakeMoney.v1/Areas/Admin/Controllers/RoleController.cs
using Library.YTB.Utils;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace ProjectMakeMoney.v1.Areas.Admin.Controllers
{
    [Authorize(Roles = "TL0002")]
    public class RoleController : Controller
    {
        private Library.YTB.DA.Role.DA_Role da_role = new Library.YTB.DA.Role.DA_Role();
        private Library.YTB.Utils.ApiResult apiResult = null;
        // GET: Admin/Role
        public ActionResult Index()
        {
            return View(da_role.actionIndex());
        }

        public ActionResult Create()
        {
            return View();
        }

        public ActionResult Edit(int id)
        {
            return View(da_role.actionEdit(id));
        }

        [HttpPost]
        public ActionResult Edit(int RoleID, int[] AuthorID)
        {
            return View(da_role.Edit(RoleID,AuthorID));
        }

        [HttpPost]
        public ActionResult Create(string code, string name, int[] AuthorID)
        {
            Library.YTB.BO.Models.Role rl = da_role.Create(code, name, AuthorID);
            if (rl != null)
                return View(rl);
            return View();
        }

        [HttpPost]
        public ActionResult Delete(int RoleID)
        {
            apiResult = da_role.Delete(RoleID);
            return Json(apiResult, JsonRequestBehavior.AllowGet);
        }
    }
}

ProjectMakeMoney.v1/ProjectMakeMoney.v1/Areas/Admin/Controllers/VideoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using System.Text.RegularExpressions;
using Library.YTB.Utils;
using Library.YTB.BO.Models;

namespace ProjectMakeMoney.v1.Areas.Admin.Controllers
{
    [Authorize(Roles = "TL0007")]
    public class VideoController : Controller
    {
        private Library.YTB.DA.Videos.Videos da_video = null;
        private Library.YTB.Utils.ApiResult apiResult = null;
        // GET: Admin/Video

        [HttpGet]
        public ActionResult Edit(int? ID)
        {
            da_video = new Library.YTB.DA.Videos.Videos();
            if (!da_video.GetItem(ID))
                return RedirectToAction("Index", "Home");
            ViewBag.id = ID;
            return View();
        }

        [HttpGet]
        public ActionResult Detail(int? ID)
        {
            da_video = new Library.YTB.DA.Videos.Videos();
            if (!da_video.GetItem(ID))
                return RedirectToAction("Index", "Home");
            ViewBag.id = ID;
            return View();
        }

        public ActionResult Index(long? idkenh)
        {
            ViewBag.idkenh = idkenh;
            return View();
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpGet]
        public ActionResult GET(PagingParam pagingParam, string tieude, bool? thinhhanh, bool? dexuat, bool? trangthai)
        {
            da_video = new Library.YTB.DA.Videos.Videos();
            apiResult = da_video.GET(pagingParam, tieude, thinhhanh, dexuat, trangthai);
            return Json(apiResult, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult GetListKenh(long? id)
        {
            da_video = new Library.YTB.DA.Videos.Videos();
            apiResult = da_video.GetListKenh(id);
            return Json(apiResult, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult GETID(long? id)
        {
            da_video = new Library.YTB.DA.Videos.Videos();
            apiResult = da_video.GETID(id);
            return Json(apiResult, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult Create(Video vd)
        {
            da_video = new Library.YTB.DA.Videos.Videos(User.Identity.Name);
            apiResult = da_video.Create(vd);
            return Json(apiResult, JsonRequestBehavior.AllowGet);
        }

        [HttpPut]
        public ActionResult Edit(long id, Video vd)
        {
            if (!ModelState.IsValid)
                return Json(new ApiResult() { success = false, message = "không thể tạo yêu cầu", data = null }, JsonRequestBehavior.AllowGet);

            da_video = new Library.YTB.DA.Videos.Videos(User.Identity.Name);
            apiResult = da_video.Edit(id,vd);
            return Json(apiResult, JsonRequestBehavior.AllowGet);
        }

        [HttpPut]
        public ActionResult isActive(long id)
        {
            if (!ModelState.IsValid)
                return Json(new ApiResult() { success = false, message = "không thể tạo yêu cầu", data = null }, JsonRequestBehavior.AllowGet);

            da_video = new Library.YTB.DA.Videos.Videos(User.Identity.Name);
            apiResult = da_video.isActive(id);
            return Json(apiResult, JsonRequestBehavior.AllowGet);
        }

        [HttpDelete]
        public ActionResult DELETE(long id)
        {
            da_video = new Library.YTB.DA.Videos.Videos(User.Identity.Name);
            apiResult = da_video.DELETE(id);
            return Json(apiResult, JsonRequestBehavior.AllowGet);
        }
    }
}

ProjectMakeMoney.v1/ProjectMakeMoney.v1/Areas/Admin/Views/Shared/_Modal.cshtml
@{
    Layout = null;
}

<div class="modal modal-default fade" id="modal-alert">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title">Thông báo</h4>
            </div>
            <div class="modal-body" style="background-color: #ffffff !important;">
                <p id="alert-body" style="color: #000;font-style: italic;"></p>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<!-- /.modal -->

ProjectMakeMoney.v1/ProjectMakeMoney.v1/Areas/Admin/Views/Shared/_mainSidebar.cshtml
@using Library.YTB.BO.Models;
@using Library.YTB.Utils;
@{
    Layout = null;
    AppDbContext db = new AppDbContext();
}
@if (User.Identity.IsAuthenticated)
{
    int? RoleID = db.Users.Where(x => x.username == User.Identity.Name).Select(x => x.role_id).FirstOrDefault(); ;

    <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
            <!-- Sidebar user panel -->
            <div class="user-panel">
                <div class="pull-left image">
                    <img src="~/Lib/dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">
                </div>
                <div class="pull-left info">
                    <p>Alexander Pierce</p>
                    <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
                </div>
            </div>
            <!-- search form -->
            <form action="#" method="get" class="sidebar-form">
                <div class="input-group">
                    <input type="text" name="q" class="form-control" placeholder="Search...">
                    <span class="input-group-btn">
                        <button type="submit" name="search" id="search-btn" class="btn btn-flat">
                            <i class="fa fa-search"></i>
                        </button>
                    </span>
                </div>
            </form>
            <!-- /.search form -->
            <!-- sidebar menu: : style can be found in sidebar.less -->
            <ul class="sidebar-menu" data-widget="tree">
                <li class="header">MAIN NAVIGATION</li>
                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-dashboard"></i> <span>Dashboard</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li><a href="@Url.Action("Index", "Caidatchung" )"><i class="fa fa-circle-o"></i> Cài đặt trang</a></li>
                    </ul>
                </li>
                @if (Utils.Decentralization(User.Identity.Name, "TL0002"))
                {
                 
                    <li class="treeview">
                        <a href="#">
                            <i class="fa fa-dashboard"></i> <span>Quản lí Chức vụ</span>
                            <span class="pull-right-container">
                                <i class="fa fa-angle-left pull-right"></i>
                            </span>
                        </a>
                        <ul class="treeview-menu">
                            <li><a href="@Url.Action("Index", "Role" )"><i class="fa fa-circle-o"></i> Danh sách</a></li>

                            <li><a href="@Url.Action("Create", "Role" )"><i class="fa fa-circle-o"></i> Tạo mới</a></li>
                        </ul>
                    </li>
                }


                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-dashboard"></i> <span>Quản lí Tài khoản</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li><a href="@Url.Action("Index", "User" )"><i class="fa fa-circle-o"></i> Danh sách</a></li>
                        <li><a href="@Url.Action("Create", "User" )"><i class="fa fa-circle-o"></i> Tạo mới</a></li>
                    </ul>
                </li>

                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-dashboard"></i> <span>Quản lí Địa chỉ</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li><a href="@Url.Action("Diachi", "Home" )"><i class="fa fa-circle-o"></i> Danh sách</a></li>
                        <li><a href="@Url.Action("Create", "MD_TinhThanh" )"><i class="fa fa-circle-o"></i> Tạo Tỉnh, thành</a></li>
                        <li><a href="@Url.Action("Create", "MD_QuanHuyen" )"><i class="fa fa-circle-o"></i> Tạo Quận, huyện</a></li>
                        <li><a href="@Url.Action("Create", "MD_PhuongXa" )"><i class="fa fa-circle-o"></i> Tạo Phường, xã</a></li>
                    </ul>
                </li>

                @if (Utils.Decentralization(User.Identity.Name, "TL0011"))
                {
                    <li class="treeview">
                        <a href="#">
                            <i class="fa fa-dashboard"></i> <span>Quản lí Menu</span>
                            <span class="pull-right-container">
                                <i class="fa fa-angle-left pull-right"></i>
                            </span>
                        </a>
                        <ul class="treeview-menu">

                            <li><a href="@Url.Action("Index", "Menu" )"><i class="fa fa-circle-o"></i> Danh sách</a></li>


                            <li><a href="@Url.Action("Create", "Menu" )"><i class="fa fa-circle-o"></i> Tạo mới</a></li>

                        </ul>
                    </li>
                }

                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-dashboard"></i> <span>Quản lí giao dịch</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li><a href="@Url.Action("Index", "Giaodich" )"><i class="fa fa-circle-o"></i> Danh sách giao dịch</a></li>
                        <li><a href="@Url.Action("Index", "Giaodich" )"><i class="fa fa-circle-o"></i> Danh sách chuyển tiền</a></li>
                    </ul>
                </li>

                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-dashboard"></i> <span>Quản lí Kênh</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li><a href="@Url.Action("Index", "Kenh" )"><i class="fa fa-circle-o"></i> Danh sách Kênh</a></li>
                        <li><a href="@Url.Action("Create", "Kenh" )"><i class="fa fa-circle-o"></i> Tạo kênh</a></li>
                    </ul>
                </li>
                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-dashboard"></i> <span>Quản lí Video</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li><a href="@Url.Action("Index", "Video" )"><i class="fa fa-circle-o"></i> Danh sách video</a></li>
                        <li><a href="@Url.Action("Create", "Video" )"><i class="fa fa-circle-o"></i> Tạo video</a></li>
                    </ul>
                </li>

                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-dashboard"></i> <span>Quản lí Sản phẩm</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li><a href="@Url.Action("Index", "Sanpham" )"><i class="fa fa-circle-o"></i> Danh sách Sản phẩm</a></li>
                        <li><a href="@Url.Action("Create", "Sanpham" )"><i class="fa fa-circle-o"></i> Tạo Sản phẩm</a></li>
                    </ul>
                </li>

                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-dashboard"></i> <span>Quản lí Ngân hàng</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li><a href="@Url.Action("Index", "MD_NganHang" )"><i class="fa fa-circle-o"></i> Danh sách Ngân hàng</a></li>
                        <li><a href="@Url.Action("Create", "MD_NganHang" )"><i class="fa fa-circle-o"></i> Tạo ngân hàng</a></li>
                    </ul>
                </li>

                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-dashboard"></i> <span>Quản lí người dùng</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li><a href="@Url.Action("Index", "Khachhang" )"><i class="fa fa-circle-o"></i> Danh sách người dùng</a></li>
                        <li><a href="@Url.Action("Create", "Khachhang" )"><i class="fa fa-circle-o"></i> Tạo người dùng</a></li>
                    </ul>
                </li>
            </ul>
        </section>
        <!-- /.sidebar -->
    </aside>
}
else
{
    <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
            <!-- Sidebar user panel -->
            <div class="user-panel">
                <div class="pull-left image">
                    <img src="~/Lib/dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">
                </div>
                <div class="pull-left info">
                    <p>Alexander Pierce</p>
                    <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
                </div>
            </div>
            <!-- search form -->
            <form action="#" method="get" class="sidebar-form">
                <div class="input-group">
                    <input type="text" name="q" class="form-control" placeholder="Search...">
                    <span class="input-group-btn">
                        <button type="submit" name="search" id="search-btn" class="btn btn-flat">
                            <i class="fa fa-search"></i>
                        </button>
                    </span>
                </div>
            </form>
            <!-- /.search form -->
            <!-- sidebar menu: : style can be found in sidebar.less -->
            <ul class="sidebar-menu" data-widget="tree">
                <li class="header">MAIN NAVIGATION</li>

            </ul>
        </section>
        <!-- /.sidebar -->
    </aside>
}