ProjectMakeMoney.v1/ProjectMakeMoney.v1/Controllers/ForgotPasswordController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using System.Data;

namespace ProjectMakeMoney.v1.Controllers
{
    public class ForgotPasswordController : Controller
    {
        private Library.YTB.DA.Login.ForgotPassword objForgotPassword = new Library.YTB.DA.Login.ForgotPassword();
        private Library.YTB.Utils.ApiResult apiResult = null;
        // GET: ForgotPassword
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ChangeThePassword(string username, string otp)
        {
            if (!objForgotPassword.CheckYeucaudoimatkhau(username, otp))
                return RedirectToAction("Index", "Home");
            ViewBag.Username = username;
            ViewBag.OTP = otp;
            return View();
        }
        [HttpPost]
        public ActionResult Post(string username, string Email)
        {
            apiResult = objForgotPassword.EmailRequestCode(username, Email);
            return Json(apiResult, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult ChangePassword(string OTP, string username, string Password, string PasswordComfirm)
        {
            apiResult = objForgotPassword.ChangePassword(OTP, username, Password, PasswordComfirm);
            return Json(apiResult, JsonRequestBehavior.AllowGet);
        }
    }
}

ProjectMakeMoney.v1/ProjectMakeMoney.v1/Controllers/LoginHomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Library.YTB.BO.Models;
using System.Data.Entity;
using System.Data;
using System.Web.Security;

namespace ProjectMakeMoney.v1.Controllers
{
    public class LoginHomeController : Controller
    {
        private string message = string.Empty;
        private Library.YTB.DA.Login.LoginHome objloginHome = null;
        // GET: LoginHome
        public ActionResult Index()
        {
            if (User.Identity.IsAuthenticated)
            {
                objloginHome = new Library.YTB.DA.Login.LoginHome(User.Identity.Name);
                if (objloginHome.UserGetLogin() == 2)
                    return  Content("<script>window.location.assign('/dashboard');</script>");
                if (objloginHome.UserGetLogin() == 1)
                    return RedirectToRoute("Admin-Home-Index");
            }
            return View();
        }

        [HttpPost]
        public ActionResult LoginUser(string username, string password)
        {
            objloginHome = new Library.YTB.DA.Login.LoginHome(string.Empty);
            if (!objloginHome.login(username, password, ref message))
                return Json(new { success = false, message = message }, JsonRequestBehavior.AllowGet);
            return Json(new { success = true, action = "/dashboard", message = "Đăng nhập thành công" }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            Response.Cookies.Remove(FormsAuthentication.FormsCookieName);
            Response.Cache.SetExpires(DateTime.Now.AddSeconds(-1));
            HttpCookie cookie = HttpContext.Request.Cookies[FormsAuthentication.FormsCookieName];
            if (cookie != null)
            {
                cookie.Expires = DateTime.Now.AddDays(-1);
                Response.Cookies.Add(cookie);
            }

            return RedirectToAction("Index");
        }
    }
}

ProjectMakeMoney.v1/ProjectMakeMoney.v1/Views/LoginHome/Index.cshtml
@{
    Layout = null;
    string Sitename = System.Configuration.ConfigurationSettings.AppSettings["Sitename"].ToString();
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>@Html.Raw(Sitename) | Đăng nhập tài khoản</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="~/Lib/bower_components/bootstrap/dist/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/Lib/bower_components/font-awesome/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="~/Lib/bower_components/Ionicons/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/Lib/dist/css/AdminLTE.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="~/Lib/plugins/iCheck/square/blue.css">
    <!-- alertifyjs -->
    <link href="~/Lib/alertifyjs/css/alertify.min.css" rel="stylesheet" />
    <link href="~/Lib/alertifyjs/css/alertify.rtl.min.css" rel="stylesheet" />
    <link href="~/Lib/alertifyjs/css/themes/default.min.css" rel="stylesheet" />
    <link href="~/Lib/alertifyjs/css/themes/default.rtl.min.css" rel="stylesheet" />
    <link href="~/Lib/alertifyjs/css/themes/semantic.css" rel="stylesheet" />
    <link href="~/Lib/alertifyjs/css/themes/semantic.rtl.css" rel="stylesheet" />
    <!--loading-->
    <link href="~/Lib/loader/loading.css" rel="stylesheet" />
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- Google Font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
    <style>
    </style>
</head>
<body class="hold-transition login-page">
    <div class="loading">Loading&#8230;</div>
    <div class="login-box">
        <div class="login-logo">
            <a href="/home" style="font-size: 25px"><b>@Html.Raw(Sitename)</b></a>
        </div>
        <!-- /.login-logo -->
        <div class="login-box-body">
            <p class="login-box-msg">Đăng nhập để bắt đầu phiên của bạn</p>
            @using (Html.BeginForm("LoginUser", "LoginHome", FormMethod.Post, new { id = "frm" }))
            {
                <div class="form-group has-feedback">
                    <input type="text" class="form-control" name="username" placeholder="username">
                    <span class="glyphicon glyphicon-user form-control-feedback"></span>
                </div>
                <div class="form-group has-feedback">
                    <input type="password" class="form-control" name="password" placeholder="Password">
                    <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                </div>
                <div class="row">

                    <!-- /.col -->
                    <div class="col-xs-4 pull-right">
                        <button type="submit" class="btn btn-primary btn-block btn-flat">Đăng nhập</button>
                    </div>
                    <!-- /.col -->
                </div>
            }
            <!-- /.social-auth-links -->
            <a href="@Url.Action("Index","ForgotPassword")">Quên mật khẩu ?</a><br>
            <a href="/registration">Chưa có tài khoản !</a><br>
        </div>
        <!-- /.login-box-body -->
    </div>
    <!-- /.login-box -->
    <!-- jQuery 3 -->
    <script src="~/Lib/bower_components/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap 3.3.7 -->
    <script src="~/Lib/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- iCheck -->
    <script src="~/Lib/plugins/iCheck/icheck.min.js"></script>
    <script src="~/Areas/Admin/notify/notify.min.js"></script>
    <!-- alertifyjs -->
    <script src="~/Lib/alertifyjs/alertify.min.js"></script>
    <script>
        $(function () {
            $('input').iCheck({
                checkboxClass: 'icheckbox_square-blue',
                radioClass: 'iradio_square-blue',
                increaseArea: '20%' /* optional */
            });
        });</script>

    <script>

        $(function () {
            $(function () {
                $(".loading").hide();
            });
        });

        var frm = $("#frm");
        frm.submit(function (e) {
            $(".loading").show();
            e.preventDefault();
            $.ajax({
                type: 'POST',
                url: frm.attr('action'),
                data: frm.serialize(),
                success: function (data) {
                    if (data.success) {
                        window.location = data.action;
                    } else { alertify.alert('Thông báo', data.message); }
                    $(".loading").hide();
                },
                error: function (data) {
                    $.notify("Tạo thông tin thất bại", { position: "top right", className: "error" });
                },
            });
        });
    </script>
</body>
</html>